---
version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.10.1
    ports:
      - 8080:8080
    volumes:
      - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: weaviate-t2v-module:1.0.0
    # "weaviate-t2v-module" is a custom text2vec-transformers module
    # that is built from this repository: https://github.com/Andrei-Aksionov/weaviate-t2v-module
    # in case you want to use prebuilt image by SeMi technologies (author of Weaviate)
    # choose from this list: https://weaviate.io/developers/weaviate/current/retriever-vectorizer-modules/text2vec-transformers.html
    # for example: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilbert-base-v3
    environment:
      ENABLE_CUDA: '0'
