###
GET http://localhost:8080/v1/schema


###
GET http://localhost:8080/v1/objects


###
GET http://localhost:8080/v1/meta


###
POST http://localhost:8080/v1/graphql HTTP/1.1
Content-Type: application/json
x-request-type: GraphQL

{
    Get {
        Author(
        where: {
            valueInt: 2,
            operator: GreaterThanEqual,
            path: ["wroteArticles"]
            }
        )
        {
            name
            wroteArticles {
                ... on Article {
                    title
                }
            }
        }
    }
}
